name: f_groceries
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  loader_search_bar: ^1.0.2
  cupertino_icons: ^0.1.2
  flutter_range_slider: "^1.0.1"
  carousel_pro: ^0.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:

 
  uses-material-design: true
  assets:
     - images/back.jpg
     - images/groceries.jpg
     - images/grtwo.jpg
     - images/grthre.jpg
     - images/veg.jpg
     - images/frozen.jpg
     - images/bev.jpg
     - images/brand_f.jpg
     - images/be.jpg
     - images/eggs.jpg
     - images/home.jpg
     - images/nonveg.jpg
     - images/apple.jpg
     - images/grapes.jpg
     - images/guava.jpg
     - images/kiwi.jpg
     - images/lemons.jpg
     - images/pineapple.jpg
     - images/tomato.jpg
     - images/gro.jpg






     - assets/address.json




